name = "MrMangoHands' SMP"
author = "MrMangoHands"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6f3acca67ec225973096bd88240ce4fd82adf5a9ea46abe9ecd0c27af3566ee"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
