name = "MrMangoHands' SMP"
author = "MrMangoHands"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0098d3d8558f9097a02a26613de18ae9fdf2098d494d693cb541ce98614c900f"

[versions]
minecraft = "1.19.2"
quilt = "0.17.8"
