name = "MrMangoHands' SMP"
author = "MrMangoHands"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1ff7afce3f6f38beb272ebab8c00b17300adf2536296b97f28e264c1d9778b3"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
