name = "MrMangoHands' SMP"
author = "MrMangoHands"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdc5b1221da76b923ae0114c4a745d1502f78c8299e77c81d4067da248c0139b"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
