name = "MrMangoHands' SMP"
author = "MrMangoHands"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bca62aa1a3e66c1b853e2b71c5a499941ccc782d44e25443135aeb66ad8909d4"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
