name = "MrMangoHands' SMP"
author = "MrMangoHands"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d7d4f703b0a16459bea18eebbe06e72d365b39365b3837b0c0ce25f2b75f6d0"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
